[package]
name = "fhcleanup"
version = "0.2.0"
authors = ["robinfriedli <robinfriedli@icloud.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
lazy_static = "1.4.0"
regex = "1.3.9"
rusty_pool = "0.4.2"
structopt = "0.3.15"